import { Vazirmatn } from "next/font/google";
import "./globals.css";

const inter = Vazirmatn({ subsets: ["arabic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-ir" dir="rtl">
      <body className={null}>{children}</body>
    </html>
  );
}
